//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskDevelopsToday.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTaskDevelopsToday.Resources.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 | Find out which `PULocationId` (Pick-up location ID) has the highest tip_amount on average.
        /// </summary>
        internal static string _1_button {
            get {
                return ResourceManager.GetString("1_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `PULocationId` (Pick-up location ID) has the highest tip_amount on average: {0}.
        /// </summary>
        internal static string _1_button_text {
            get {
                return ResourceManager.GetString("1_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 | Find the top 100 longest fares in terms of `trip_distance`.
        /// </summary>
        internal static string _2_button {
            get {
                return ResourceManager.GetString("2_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 100 longest fares in terms of `trip_distance`:.
        /// </summary>
        internal static string _2_button_text {
            get {
                return ResourceManager.GetString("2_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 | Find the top 100 longest fares in terms of time spent traveling.
        /// </summary>
        internal static string _3_button {
            get {
                return ResourceManager.GetString("3_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 100 longest fares in terms of time spent traveling:.
        /// </summary>
        internal static string _3_button_text {
            get {
                return ResourceManager.GetString("3_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 | Search, where part of the conditions is `PULocationId`.
        /// </summary>
        internal static string _4_button {
            get {
                return ResourceManager.GetString("4_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        internal static string _4_button_invalid_id {
            get {
                return ResourceManager.GetString("4_button_invalid_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input needed ID: .
        /// </summary>
        internal static string _4_button_selection_text {
            get {
                return ResourceManager.GetString("4_button_selection_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definite part of the conditions `PULocationId` == {0}:.
        /// </summary>
        internal static string _4_button_text {
            get {
                return ResourceManager.GetString("4_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 | Exit the program.
        /// </summary>
        internal static string _5_button {
            get {
                return ResourceManager.GetString("5_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=(localdb)\mssqllocaldb;Database=TestTaskDatabase;Trusted_Connection=True;.
        /// </summary>
        internal static string db_sql_connection {
            get {
                return ResourceManager.GetString("db_sql_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection. Try again.
        /// </summary>
        internal static string pre_selection_invalid_text {
            get {
                return ResourceManager.GetString("pre_selection_invalid_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selection: .
        /// </summary>
        internal static string pre_selection_text {
            get {
                return ResourceManager.GetString("pre_selection_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=(localdb)\mssqllocaldb;Database=master;Trusted_Connection=True;.
        /// </summary>
        internal static string server_sql_connection {
            get {
                return ResourceManager.GetString("server_sql_connection", resourceCulture);
            }
        }
    }
}
